version: '3'

services:
  productificator-api:
    container_name: productificator-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NOTION_API_TOKEN: ${NOTION_API_TOKEN}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      GOOGLE_CALENDAR_CREDENTIALS: ${GOOGLE_CALENDAR_CREDENTIALS}